# lazygit
bind -r g display-popup -d '#{pane_current_path}' -w90% -h90% -E lazygit

# Claude Code
bind -r y display-popup -d '#{pane_current_path}' -w80% -h80% -E \
  'tmux new-session -A -s "claude-$(echo #{pane_current_path} | sha256sum | cut -c1-8)" "claude"'
